/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package searcharoo;

import searcharoo.data.JSONDataLoader;
import searcharoo.ui.CommandInterface;
import searcharoo.ui.CommandInterfaceSearchProcessor;

import java.io.File;
import java.io.InputStream;
import java.io.PrintStream;

public class App {
    public final static InputStream APP_INPUT_STREAM = System.in;
    public final static PrintStream APP_PRINT_STREAM = System.out;

    public static void main(String[] args) {

        String path = "/Users/aabhushan/Code/interviews/searcharoo-proj/app/data/";
        File folder = new File(path);
        JSONDataLoader loader = new JSONDataLoader(folder);
        loader.loadFilesFromFolder();
        CommandInterfaceSearchProcessor searchProcessor = new CommandInterfaceSearchProcessor(APP_PRINT_STREAM);

        CommandInterface commandInterface = new CommandInterface(
                APP_INPUT_STREAM,
                APP_PRINT_STREAM,
                searchProcessor
        );
        commandInterface.startCommandLineInterface();
    }
}
