/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package searcharoo;

import java.io.InputStream;
import java.io.PrintStream;

public class App {
    public final static InputStream APP_INPUT_STREAM = System.in;
    public final static PrintStream APP_PRINT_STREAM = System.out;

    public static void main(String[] args) {
        CommandInterface commandInterface = new CommandInterface(APP_INPUT_STREAM, APP_PRINT_STREAM);
        commandInterface.startCommandLineInterface();
        commandInterface.exitCommandLineInterface();
    }
}
